#import "../lib.typ": *

= Lecture 1: Mathematical Tools
*dot product*
$
#a dot #a = |#a|^2 \
#a dot #b = #b dot #a
#a dot (#b + #c) = #a dot #b + #a dot #c \
(I #a) dot #b = I(#a dot #b) = #a dot (I #b) \
0 dot #a = 0 \
#a dot #b = |#a| |#b| cos theta \
$

#yellowbox("Projection of a vector on another vector", [
   *component of #b in the direction of #a*
   (length of the projection of #b onto #a)
   $
   "comp"_#a #b = frac( #a dot #b, |#a|) = |#b| cos theta
   $
   *projection of #b onto #a*
   $
   "proj"_#a #b = frac( #a dot #b, |#a|^2) #a
   $
])


- determinants of $2 times 2$ and $3 times 3$

#Definitionbox("Cross Product", [
   $ #v times #w = mat(delim: "|",
      #i, #j, #k ;
      arrow(v)_1, arrow(v)_2 , arrow(v)_3 ;
      arrow(w)_1, arrow(w)_2, arrow(w)_3 ;)
   $
   $a times b$ is perpendicular to both a and b

   *Direction of the cross product*: using the right hand rule
])

#TheoremBox("", [
   $|a times b| = |a| |b| sin theta$, where $theta$ is the angle between

   Two non-zero vectors $a$ and $b$ are parallel iff $a times b = 0$, equiv.
   the angle between them is $0$ or $pi$.
]) 

- $|#v times #w|$ is the area of the parallelogram generated by #v and #w
- $(|#v times #w|) / 2$ is the area of the triangle with sides #v, #w and $|#w - #v|$
- $|#u dot ( #v times #w)|$ is the volume of the parallel-piped generated by 

#pinkbox("", [
   $#u dot (#v times #w)$ is called the _triple dot product_ of $#u, #v, #w$ and denoted by 
   $(#u, #v, #w)$
])

#purplebox("Cross product of special Unit Vectors", [
   $
      &#i times #j = #k quad &&#j times #i = - #k \
      &#j times #k = #k quad &&#k times #j = - #i \
      &#k times #i = #k quad &&#i times #k = - #j \
   $
])

#bluebox("Properties of Cross Product", [
   cross product is not commutative, nor associaive
   
   - $#a times #b = -#b times #a$
   - $(I#a) times #b = -#b times (I#a) = I(#a times #b)$
   - $#a times (#b + #c) #a times #b + #a times #c$
   - $#a dot (#b times #c) = (#a times #b) dot #c$
   - $#a times (#b times #c) = (#a dot #c) #b - (#a dot #b) #c$
])

== Planes in 3-space

$arrow(n) dot arrow(P Q) = 0$

n is the normal, P and ! are points on the plane

#TheoremBox("Plane Equation", [
   The equation of the plane passing through $(x_0, y_0, z_0)$ with a normal vector $(A, B, C)$
   is:
   
   $
      A(x-x_0) + B(y- y_0) + C(z-z_0) &= 0 \
      A x + B y + C z &= A x_0 + B y_0 + C z_0 \ 
      A x + B y + C z &= D \ 
   $
])

#bluebox("Distance from a point to a plane", [
   //TODO: page 20
   A point $P$ has distance $d$ from the plane, where $d$ is the length of the projection
   of $arrow(P Q)$ onto the normal $n$, where $Q$ is a point on the plane.
])

#TheoremBox("Parametric equations for lines in 3-space", [
   A parametric equation of the line passing through $(x_0, y_0, z_0)$ which is
   parallel to the vector $(a, b, c)$ is given by
   $
      x &= x_0 + t a \
      y &= y_0 + t b \
      z &= z_0 + t c \
   $
   for $t in RR$

   $ t 
    = frac(x - x_0, a)
    = frac(y - y_0, b)
    = frac(z - z_0, c)
   $
])

#Examplebox([
   Find the distance from the point $P = (1, 0, −1)$ to the line
   which passes through the point $Q = (2, 1, 0)$ having direction vector
   $arrow(v) = (1, 2, 2)$

   $  
      d = sqrt(|arrow(Q P)|^2 - x^2) \
      x = |"comp"_arrow(v) arrow(Q P)| = frac(arrow(Q P) dot arrow(v), |arrow(v)|) \
      arrow(Q P) = (-1, -1, -1) \
      arrow(Q P) dot #v = (-1, -1, -1) dot (1, 2, 3) = -5 \
      x^2 = (arrow(Q P) dot #v^2)/(|#v|^2) = 25/9 \
      d = sqrt(3 - 25/9) = sqrt(2)/3
   $
])

#Examplebox([
Find the parametric equation of the line obtained by
intersecting the planes $2x − y + z = 1$ and $x + z = −1$.

determine a base point $P$ and a direction vector #v.

//TODO: 
])

